### ISSUE TITLE
Old badges to be deleted

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq_build_status#20]
- [x] Zanata => Transifex https://github.com/ManageIQ/manageiq_build_status/pull/21
- [x] coveralls - removed in https://github.com/ManageIQ/manageiq_build_status/pull/27
- [x] Gemnasium https://github.com/ManageIQ/manageiq_build_status/pull/22
- [x] build history (not deleted, but switch to github actions) https://github.com/ManageIQ/manageiq_build_status/pull/23

**Comment by chessbyte** [comment]
@Fryguy Coveralls seems to be active [here](https://coveralls.io/github/ManageIQ/manageiq?branch=master).  Why do you suggest removing the badges?

**Comment by Fryguy** [comment]
Coveralls doesn't play nice with newer simplecov which I have to update for code climate for GHA... Ultimately we will drop coveralls entirely
